<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Config;
use Faker;

use App\Models\User;
use App\Models\UserProfile;
use App\Models\City;


class UsersTableSeeder extends Seeder
{
    public function run()
    {
    	DB::table('users')->delete();

        $users = User::factory()->count(50)->create();

        $faker = Faker\Factory::create();
        $genders = Config::get('constants.genderOptions');
        $availabilities = Config::get('constants.availabilityOptions');

        foreach($users as $user){
            UserProfile::create(
                array(
                    'user_id' => $user->id,
                    'date_of_birth' => date('Y-m-d', rand(0500000000,1000000000)),
                    'city_id' => City::inRandomOrder()->first()->id,
                    'bio_short' => $faker->text($maxNbChars = 160),
                    'bio_long' => $faker->text($maxNbChars = 2000),
                    'first_name' => $faker->firstName,
                    'last_name' => $faker->lastName,
                    'gender' => $genders[array_rand($genders)],
                    'availability' => $availabilities[array_rand($availabilities)],
                )
            );
        }

        $this->create_user_for_postman();
    }

    /*
     *   Selects one of the entries generated by User::factory()
     *   and updates with the authentication credentials you wish
     *   to use when testing the API with Postman.
     *   WATCH: https://www.youtube.com/watch?v=aJ10nbRoD8Q&ab_channel=CBTNuggets
     */
    private function create_user_for_postman()
    {
        $user = User::find(1);
        $data = [
            'username' => "ryan",
            'email' => "ryan@x.com"
        ];
        $user->update($data);
    }
}