<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use App\Models\User;


class UsersTableSeeder extends Seeder
{
    public function run()
    {
    	DB::table('users')->delete();

        $users = User::factory()->count(50)->create();

        // *REVISIT* this had to be commented out due to tests failing when running `php artisan test`. There seems to be no User with id 1 when some tests execute
        // $this->create_user_for_postman();
    }

    /*
     *   Selects one of the entries generated by User::factory()
     *   and updates with the authentication credentials you wish
     *   to use when testing the API with Postman.
     *   WATCH: https://www.youtube.com/watch?v=aJ10nbRoD8Q&ab_channel=CBTNuggets
     */
    private function create_user_for_postman()
    {
        $user = User::find(1);
        $data = [
            'username' => "ryan",
            'email' => "ryan@x.com"
        ];
        $user->update($data);
    }
}